[profile.default]
solc-version = "0.8.20"
src = "contracts"
out = "build"
allow_paths = ["../.."]
libs = ["../../node_modules", "../../lib"]
remappings = [
    "@wealth-of-wisdom/staking/=../staking/",
    "@wealth-of-wisdom/nft/=./",
    "@wealth-of-wisdom/vesting=../vesting/",
    "@openzeppelin/=../../node_modules/@openzeppelin/",
]
gas_reports = ["*"]

[fuzz]
runs = 256
seed = "0x1"
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/tree/master/config