[profile.default]
src = "contracts"
out = "build"
allow_paths = ["../.."]
libs = ["../../node_modules", "../../lib"]
remappings = [
    '@wealth-of-wisdom/staking/contracts/=../../packages/stakings/contracts/',
    '@wealth-of-wisdom/staking/contracts/=../../packages/vesting/contracts/',
    '@openzeppelin/=../../node_modules/@openzeppelin/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config