const TESTNET_NETWORKS = ["sepolia", "arbitrumSepolia"]
const MAINNET_NETWORKS = ["ethereum", "arbitrumOne"]
const PERCENTAGE_DIVISOR = 100
const WOW_TOKEN_DECIMALS = 18
const DAILY_UNLOCK_TYPE_NUM = 0
const MONTHLY_UNLOCK_TYPE_NUM = 1
const DAILY_UNLOCK_TYPE_STR = "DAILY"
const MONTHLY_UNLOCK_TYPE_STR = "MONTHLY"

module.exports = {
    TESTNET_NETWORKS,
    MAINNET_NETWORKS,
    PERCENTAGE_DIVISOR,
    WOW_TOKEN_DECIMALS,
    DAILY_UNLOCK_TYPE_NUM,
    MONTHLY_UNLOCK_TYPE_NUM,
    DAILY_UNLOCK_TYPE_STR,
    MONTHLY_UNLOCK_TYPE_STR,
}
