[profile.default]
src = "contracts"
out = "build"
allow_paths = ["../.."]
libs = ["../../node_modules", "../../lib"]
remappings = [
    "@openzeppelin/=../../node_modules/@openzeppelin/",
    "@wealth-of-wisdom/vesting=../../packages/vesting",
    "@wealth-of-wisdom/staking=../../packages/staking",
]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config