[profile.default]
solc-version = "0.8.20"
src = "contracts"
out = "build"
allow_paths = ["../.."]
libs = ["../../node_modules", "../../lib"]
remappings = [
    "@openzeppelin/=../../node_modules/@openzeppelin/",
]
gas_reports = ["*"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config